[window]
opacity = 0.85
blur = true
dynamic_padding = false

[env]
WINIT_X11_SCALE_FACTOR="1.0"

[font]
normal = {family="DepartureMono Nerd Font Mono", style="Regular"}
bold = {family="CaskaydiaCove Nerd Font Mono", style="Regular"}
italic = {family="CaskaydiaCove Nerd Font Mono", style="Regular"}
size = 11
builtin_box_drawing = true

[colors]
transparent_background_colors=true

[colors.primary]
background='0x16171E'
foreground='0xD1D2D3'

[colors.normal]
black = '0x000000'
red = '0xE68E8E'
green = '0x83AC8E'
yellow = '0xF5B78A'
blue = '0x9BB8DC'
magenta = '0xBAACE2'
cyan = '0x00C5C7'
white = '0xC7C7C7'

[colors.bright]
black = '0x676767'
red = '0xFF6D67'
green = '0x5FF967'
yellow = '0xFEFB67'
blue = '0x6871FF'
magenta = '0xFF76FF'
cyan = '0x5FFDFF'
white = '0xFEFFFF'

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
